Feature/source block support
jsonreeder/vscode-org-mode pull request #108
Opened 2018-05-29 07:06 UTC by AdrieanKhisbe

### Implement Support for coding block, and generic block with syntax highlight and folding

I took inspiration from vscode markdown plugin, but instead to duplicate the scope definition by hand, I prefered to generate it from a language specification. This is done by the `populate-syntax.js` script that regenerate the grammar from the config and a template (which is the original grammar). This can be invoked with `npm run fixtures`

Can't wait to hear from your feedbacks @ajtoo ! 😃 
Feel free to ask any question.

#### Here is a preview:

<img width="286" alt="capture d ecran 2018-05-28 23 52 48" src="https://user-images.githubusercontent.com/2601132/40630727-67772c00-62d5-11e8-8cee-b0ca77f01e57.png">

Should close #103

2018-06-14 18:08 UTC, nbessi reviewed
Nice thanks for the feature. I'm not a vscode extention expert but I'll do a functional test

2018-06-14 18:30 UTC, nbessi approved these changes
Works like a charm. 
No performance issue event with a script that generate a lot of src blocks.

Latex syntax highlight would be a plus :package: 
:+1:

2018-06-14 18:31 UTC, nbessi approved these changes

2018-07-02 18:01 UTC, nbessi commented
no one on this PR ?

2018-07-25 18:24 UTC, AdrieanKhisbe commented
@nbessi Will add the latex support in the coming days both for the `#+BEGIN_SRC  latex` and the `#+BEGIN_LATEX`

2018-07-26 14:59 UTC, AdrieanKhisbe commented
@nbessi done.
In the end I did not do a specific syntax for `#+BEGIN_LATEX`, since it has been superseeded by `#+BEGIN_EXPORT latex`

2018-08-07 21:30 UTC, sipi reviewed
I'm not sure where is the bug but when I write something like:
```
#+begin_src java
public class Test {
    public static void main(String args[]) {
        System.out.println("ok, I'm highlighted!")
    }
}
#+end_src
public class Test {
    public static void main(String args[]) {
        System.out.println("Oups, I'm highlighted too!")
    }
}
** class diagram (still highlighted!)
```
the coloration correctly start but fail to stop with lower case #+end_src

Otherwise, it's a very good job thanks.

2018-08-08 15:57 UTC, sipi requested changes
fix the coloration bug on ``#+end_src`` in lower case by applying following patch on each occurence in ``syntaxes/org.tmLanguage.json`` and ``syntaxes/populate-syntax.js`` : 
``` diff
-                            "while": "(^|\\G)(?!\\s*#\\+END_SRC\\s*)",
+                            "while": "(?i)(^|\\G)(?!\\s*#\\+END_SRC\\s*)",
```

2018-08-13 10:28 UTC, AdrieanKhisbe commented
Good spot @sipi , going to fix it right away

2018-08-13 10:33 UTC, AdrieanKhisbe commented
Fix done, if you (@sipi) could check if bug is gone that would be awesome :)

2018-08-22 08:03 UTC, sipi approved these changes
Everything seems to be ok.

2018-08-22 13:53 UTC, sipi requested changes
Hi @AdrieanKhisbe, 
I found an other similar issue when adding whitespaces after `#+END_SRC      `…

I suggest change below:
``` diff
--- a/syntaxes/org.tmLanguage.template.json
+++ b/syntaxes/org.tmLanguage.template.json
@@ -61,7 +61,7 @@
                 {
                     "name": "meta.block.${2:/downcase}",
                     "begin": "(?i)(?:^|\\G)(?:\\s*)(#\\+BEGIN_(\\w+))\\b\\s*(.*)$",
-                    "end": "(?i)(?:^|\\G)(?:\\s*)(#\\+END_\\2)$",
+                    "end": "(?i)(?:^|\\G)(?:\\s*)(#\\+END_\\2)\\s*$",
                     "beginCaptures": {
                         "1": {
                             "name": "keyword.control.block.org"
```

2018-08-24 12:40 UTC, AdrieanKhisbe commented
@sipi Issue solved! :)

2018-08-24 13:37 UTC, sipi approved these changes
:)

2018-09-11 18:50 UTC, sipi approved these changes
I tested, it works well and it is very useful.

2018-09-11 19:34 UTC, merged

2018-09-12 13:32 UTC, AdrieanKhisbe commented
@sipi AWESOME!! :) 
🎉

2021-01-30 21:06 UTC, zetashift commented
@AdrieanKhisbe sorry for the ping but this is quite the old PR, so I want to ask:

How would one go about adding more highlighting support? I'm looking for Nim and Elixir in particular.

2021-02-01 08:02 UTC, AdrieanKhisbe commented
No problem @zetashift,

Reverse engineering my old pr, you would need to add to the [`programmingLanguages ` list](https://github.com/vscode-org-mode/vscode-org-mode/pull/108/files#diff-6e445596869c79baf9a24ef9a3be8d140141b19abb3d31fc5714d89c4e868af3R5) then `npm run generate-syntax` to update the generated syntax definition.

More instruction on how to find language code [there](https://github.com/vscode-org-mode/vscode-org-mode/pull/108/files#diff-6e445596869c79baf9a24ef9a3be8d140141b19abb3d31fc5714d89c4e868af3R44-R45)

2021-02-01 12:35 UTC, zetashift commented
Got it working! it was as easy as adding it to the programmingLanguages list and running the command.

Not entirely sure if this is PR worthy?

2021-02-01 12:41 UTC, AdrieanKhisbe commented
Cool :)

@zetashift I think this is worthy.
Even more if you add some languages that were overlooked when I made the original PR.

(and that could be an opportunity to refresh a bit extension dependencies)

2021-02-01 12:54 UTC, zetashift commented
Alright I'll make a PR and add some languages that I know of.

Last question:
How would one go about adding indentation support to something like Python? As far as I tested currently the only way to get it by opening up some curly braces `{}` and pressing Enter.

2021-02-02 11:06 UTC, AdrieanKhisbe commented
Hello @zetashift , I saw the PR, review incoming.

about Python, do you mean that block are not working correctly?
If so, please provide a text sample and screenshot. (might be better to open a dedicated issue :))